name: syuboard

on:
  push:
    branches: 
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          ssh_private_key: ${{ secrets.FTP_PASSWORD }}
          remote_path: ${{ secrets.FTP_REMOTE_ROOT }}
          local_path: project/
          args: '-o ConnectTimeout=5'