name: syuboard

on:
  push:
    branches: 
      - main

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftps
          server-dir: ${{ secrets.FTP_REMOTE_ROOT }}
          local-dir: project/